// <auto-generated />
using System;
using MarvicSolution.DATA.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarvicSolution.DATA.Migrations
{
    [DbContext(typeof(MarvicDbContext))]
    [Migration("20220331180615_db-v1")]
    partial class dbv1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarvicSolution.DATA.Entities.App_Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updator")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("App_Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea586555-af1d-4536-9e8c-29f00adef527"),
                            ConcurrencyStamp = "64d601c5-64ab-4c31-b8bd-74e6970f47b5",
                            Creator = "KhanhND",
                            DateCreated = new DateTime(2022, 4, 1, 1, 6, 14, 808, DateTimeKind.Local).AddTicks(5392),
                            IsDeleted = 0,
                            Name = "Project Manager",
                            UpdateDate = new DateTime(2022, 4, 1, 1, 6, 14, 808, DateTimeKind.Local).AddTicks(8895),
                            Updator = "KhanhND"
                        },
                        new
                        {
                            Id = new Guid("a31bfd28-35fa-419a-b03f-fe687112dc5c"),
                            ConcurrencyStamp = "7b5eadcb-e7c6-443a-84a2-6301b50756c5",
                            Creator = "KhanhND",
                            DateCreated = new DateTime(2022, 4, 1, 1, 6, 14, 808, DateTimeKind.Local).AddTicks(9828),
                            IsDeleted = 0,
                            Name = "Member",
                            UpdateDate = new DateTime(2022, 4, 1, 1, 6, 14, 808, DateTimeKind.Local).AddTicks(9834),
                            Updator = "KhanhND"
                        },
                        new
                        {
                            Id = new Guid("0bd0e4cd-9a05-4588-a75f-1625492156b3"),
                            ConcurrencyStamp = "5c68add5-814d-4033-aa61-5771c33597d8",
                            Creator = "KhanhND",
                            DateCreated = new DateTime(2022, 4, 1, 1, 6, 14, 808, DateTimeKind.Local).AddTicks(9841),
                            IsDeleted = 0,
                            Name = "Viewer",
                            UpdateDate = new DateTime(2022, 4, 1, 1, 6, 14, 808, DateTimeKind.Local).AddTicks(9842),
                            Updator = "KhanhND"
                        });
                });

            modelBuilder.Entity("MarvicSolution.DATA.Entities.App_User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("App_User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e341a8f6-dc1b-4829-94fb-316b6bac99b6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dac0f81e-fabc-435b-9f0a-df6aee906b10",
                            Department = "Khoang 1 HN",
                            Email = "khanhnd@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Nguyen Duy Khanh",
                            IsDeleted = 0,
                            JobTitle = "Project Manager",
                            LockoutEnabled = false,
                            Organization = "Company TechNo1",
                            Password = "KhanhND123@",
                            PhoneNumber = "0989878767",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "KhanhND"
                        },
                        new
                        {
                            Id = new Guid("346f2520-6295-4734-8868-6ca75258e7c1"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "404b4074-dafc-4bd8-a3b5-c7434f455334",
                            Department = "Khoang 2 HCM",
                            Email = "nhantt@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Tran Thien Nhan",
                            IsDeleted = 0,
                            JobTitle = "Member Job Title",
                            LockoutEnabled = false,
                            Organization = "Company PizzaHub",
                            Password = "NhanTT123@",
                            PhoneNumber = "0336355563",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "NhanTT"
                        },
                        new
                        {
                            Id = new Guid("7a370bac-b796-454d-84cf-18c603102ca2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f5c0b33b-51f1-4130-8ace-d1720ef6c990",
                            Department = "Khoang 10 DN",
                            Email = "nhant1@gmail.com",
                            EmailConfirmed = false,
                            FullName = "Tran Thanh Nhan",
                            IsDeleted = 0,
                            JobTitle = "Director",
                            LockoutEnabled = false,
                            Organization = "Company Marketing Hanzu",
                            Password = "NhanTTT1Cute@",
                            PhoneNumber = "0345677456",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "NhanTTT1"
                        });
                });

            modelBuilder.Entity("MarvicSolution.DATA.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id_Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Lead")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_ProjectType")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Updator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a42b223b-faec-48e3-8e28-51fe1b22fa7c"),
                            DateCreated = new DateTime(2021, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnd = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2021, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_Lead = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_ProjectType = new Guid("77b88991-f823-4301-b452-1b14ca44d5cb"),
                            Id_Updator = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = 0,
                            Key = "PA",
                            Name = "Project A",
                            UpdateDate = new DateTime(2021, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("89fad9a0-690d-46e8-a2fe-c6cc50350eaf"),
                            DateCreated = new DateTime(2021, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnd = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2021, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_Lead = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_ProjectType = new Guid("77b88991-f823-4301-b452-1b14ca44d5cb"),
                            Id_Updator = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = 0,
                            Key = "PB",
                            Name = "Project B",
                            UpdateDate = new DateTime(2021, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a5329d06-9d32-4a54-b816-906dfbbd288c"),
                            DateCreated = new DateTime(2021, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnd = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2021, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_Lead = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_ProjectType = new Guid("21c68955-ea3e-4b41-8ec5-ef816c912f1a"),
                            Id_Updator = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = 0,
                            Key = "PC",
                            Name = "Project C",
                            UpdateDate = new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MarvicSolution.DATA.Entities.ProjectType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updator")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77b88991-f823-4301-b452-1b14ca44d5cb"),
                            Creator = "User A",
                            IsDeleted = 0,
                            Name = "Marketing",
                            UpdateDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = "User A_Update"
                        },
                        new
                        {
                            Id = new Guid("21c68955-ea3e-4b41-8ec5-ef816c912f1a"),
                            Creator = "User B",
                            IsDeleted = 0,
                            Name = "Development Program",
                            UpdateDate = new DateTime(2021, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = "User B_Update"
                        },
                        new
                        {
                            Id = new Guid("cc6c38be-7461-4f0c-b3dd-722477375d61"),
                            Creator = "User C",
                            IsDeleted = 0,
                            Name = "Accounting",
                            UpdateDate = new DateTime(2015, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = "User C_Update"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("App_RoleClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("App_UserClaim");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("App_UserLogin");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable("App_UserRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("App_UserToken");
                });
#pragma warning restore 612, 618
        }
    }
}
