// <auto-generated />
using System;
using MarvicSolution.DATA.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarvicSolution.DATA.Migrations
{
    [DbContext(typeof(MarvicDbContext))]
    [Migration("20220423154111_update_table_comment")]
    partial class update_table_comment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarvicSolution.DATA.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Question")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsAnswer")
                        .HasColumnType("int");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Answer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("69a58c4b-c2e1-455d-9559-4169162c1bbf"),
                            Id_Question = new Guid("da1969f2-3008-49d3-8281-030b4c343c5d"),
                            IsAnswer = 0,
                            IsDeleted = 1,
                            Name = "Ans A1-1"
                        },
                        new
                        {
                            Id = new Guid("4a69753c-f865-404f-abd8-43c350222189"),
                            Id_Question = new Guid("da1969f2-3008-49d3-8281-030b4c343c5d"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans A1-2"
                        },
                        new
                        {
                            Id = new Guid("4e257ba8-35d3-45f0-baac-f2b0b98fbedd"),
                            Id_Question = new Guid("da1969f2-3008-49d3-8281-030b4c343c5d"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans A1-3"
                        },
                        new
                        {
                            Id = new Guid("146980c0-f9a3-4457-8b03-e8511fdfdbc1"),
                            Id_Question = new Guid("da1969f2-3008-49d3-8281-030b4c343c5d"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans A1-4"
                        },
                        new
                        {
                            Id = new Guid("4c9b7cda-859b-4c26-b2df-2002073bbd84"),
                            Id_Question = new Guid("5570f4ee-0f7d-4a48-be63-bc011555ddd2"),
                            IsAnswer = 1,
                            IsDeleted = 0,
                            Name = "Ans A2-1"
                        },
                        new
                        {
                            Id = new Guid("944115d0-9566-4e58-b711-23f8869df029"),
                            Id_Question = new Guid("5570f4ee-0f7d-4a48-be63-bc011555ddd2"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans A2-2"
                        },
                        new
                        {
                            Id = new Guid("2adad43f-5cc2-48d9-97af-51ad79e41160"),
                            Id_Question = new Guid("5570f4ee-0f7d-4a48-be63-bc011555ddd2"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans A2-3"
                        },
                        new
                        {
                            Id = new Guid("1616a299-6b7b-4573-abfa-2c3d40641ab1"),
                            Id_Question = new Guid("5570f4ee-0f7d-4a48-be63-bc011555ddd2"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans A2-4"
                        },
                        new
                        {
                            Id = new Guid("a906e299-85d6-4fa9-9138-95083438f304"),
                            Id_Question = new Guid("a8b3af9f-bae9-4b1a-89d0-808f7b8b4e56"),
                            IsAnswer = 1,
                            IsDeleted = 0,
                            Name = "Ans A3-1"
                        },
                        new
                        {
                            Id = new Guid("7afccd26-5f50-4810-aad8-ae0f53b93b0b"),
                            Id_Question = new Guid("a8b3af9f-bae9-4b1a-89d0-808f7b8b4e56"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans A3-2"
                        },
                        new
                        {
                            Id = new Guid("2b8f753c-fda8-43fa-b5e8-883852367e56"),
                            Id_Question = new Guid("a8b3af9f-bae9-4b1a-89d0-808f7b8b4e56"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans A3-3"
                        },
                        new
                        {
                            Id = new Guid("535050be-932a-4b9b-a9d7-dbb2eb2ccb25"),
                            Id_Question = new Guid("a8b3af9f-bae9-4b1a-89d0-808f7b8b4e56"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans A3-4"
                        },
                        new
                        {
                            Id = new Guid("53c26c0e-944c-4b4d-98a6-48bfabfb484b"),
                            Id_Question = new Guid("d60e8b27-d139-40d4-9cc8-3e8d09752a6a"),
                            IsAnswer = 1,
                            IsDeleted = 0,
                            Name = "Ans A4-1"
                        },
                        new
                        {
                            Id = new Guid("c4709e72-98c1-4a46-89e1-971de4143d25"),
                            Id_Question = new Guid("d60e8b27-d139-40d4-9cc8-3e8d09752a6a"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans A4-2"
                        },
                        new
                        {
                            Id = new Guid("74fe3ebc-3381-4e9f-a2f4-a6c20114d3d5"),
                            Id_Question = new Guid("d60e8b27-d139-40d4-9cc8-3e8d09752a6a"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans A4-3"
                        },
                        new
                        {
                            Id = new Guid("64d5ad49-dd7d-467f-8a8c-932d00df8bab"),
                            Id_Question = new Guid("d60e8b27-d139-40d4-9cc8-3e8d09752a6a"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans A4-4"
                        },
                        new
                        {
                            Id = new Guid("1ff50d10-dd8e-4da1-bb11-1fcbbc1e3c10"),
                            Id_Question = new Guid("1d641d48-f550-481b-adff-440ed5aa6f65"),
                            IsAnswer = 1,
                            IsDeleted = 0,
                            Name = "Ans B1-1"
                        },
                        new
                        {
                            Id = new Guid("bc8eacec-efa8-4288-b97d-d2d61be430fe"),
                            Id_Question = new Guid("1d641d48-f550-481b-adff-440ed5aa6f65"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B1-2"
                        },
                        new
                        {
                            Id = new Guid("77f88ec5-4f24-45cf-9655-3c7931e33507"),
                            Id_Question = new Guid("1d641d48-f550-481b-adff-440ed5aa6f65"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B1-3"
                        },
                        new
                        {
                            Id = new Guid("5ce3de4e-e51a-40de-983f-a15207da423e"),
                            Id_Question = new Guid("1d641d48-f550-481b-adff-440ed5aa6f65"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B1-4"
                        },
                        new
                        {
                            Id = new Guid("08139b92-015c-47e1-8f8a-50134c2e7a89"),
                            Id_Question = new Guid("b776ef62-50a5-4998-aa13-a6d3f4ca35e4"),
                            IsAnswer = 1,
                            IsDeleted = 0,
                            Name = "Ans B2-1"
                        },
                        new
                        {
                            Id = new Guid("c666592a-6d7d-4a54-9ccf-e0d866167f39"),
                            Id_Question = new Guid("b776ef62-50a5-4998-aa13-a6d3f4ca35e4"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B2-2"
                        },
                        new
                        {
                            Id = new Guid("315b2b1e-f044-418c-841d-027f89432209"),
                            Id_Question = new Guid("b776ef62-50a5-4998-aa13-a6d3f4ca35e4"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B2-3"
                        },
                        new
                        {
                            Id = new Guid("6409db52-2b3c-45fb-ac46-91d050d57eb0"),
                            Id_Question = new Guid("b776ef62-50a5-4998-aa13-a6d3f4ca35e4"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B2-4"
                        },
                        new
                        {
                            Id = new Guid("8f737006-062b-4b5a-ba2a-35eecf3a5f95"),
                            Id_Question = new Guid("7cf4e8f0-9dd9-438d-8581-57d33ad90b78"),
                            IsAnswer = 1,
                            IsDeleted = 0,
                            Name = "Ans B3-1"
                        },
                        new
                        {
                            Id = new Guid("ad954fc8-9344-40e9-8d1f-3b08490f7a7f"),
                            Id_Question = new Guid("7cf4e8f0-9dd9-438d-8581-57d33ad90b78"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B3-2"
                        },
                        new
                        {
                            Id = new Guid("4987be92-0627-4ac3-87d3-3771dc83bcf5"),
                            Id_Question = new Guid("7cf4e8f0-9dd9-438d-8581-57d33ad90b78"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B3-3"
                        },
                        new
                        {
                            Id = new Guid("fe4b0fb6-cc5c-4f1b-b617-977d76497b40"),
                            Id_Question = new Guid("7cf4e8f0-9dd9-438d-8581-57d33ad90b78"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B3-4"
                        },
                        new
                        {
                            Id = new Guid("2a9bc99a-f323-4002-b6af-7de602692ec4"),
                            Id_Question = new Guid("5d6e0ec4-cbd9-43d9-8330-4b76405808ae"),
                            IsAnswer = 1,
                            IsDeleted = 0,
                            Name = "Ans B4-1"
                        },
                        new
                        {
                            Id = new Guid("91bbfe96-d736-4b9d-b592-009dd0a28801"),
                            Id_Question = new Guid("5d6e0ec4-cbd9-43d9-8330-4b76405808ae"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B4-2"
                        },
                        new
                        {
                            Id = new Guid("804e778f-eeeb-4375-8486-e9991e0dd8b3"),
                            Id_Question = new Guid("5d6e0ec4-cbd9-43d9-8330-4b76405808ae"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B4-3"
                        },
                        new
                        {
                            Id = new Guid("9e213971-75f6-48cd-b948-a3390c767eb7"),
                            Id_Question = new Guid("5d6e0ec4-cbd9-43d9-8330-4b76405808ae"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B4-4"
                        },
                        new
                        {
                            Id = new Guid("1bf39dbf-863e-42d9-94ae-3ba9745b5c84"),
                            Id_Question = new Guid("f0869ff6-3127-4714-a75d-720d198c59e5"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B4-4"
                        },
                        new
                        {
                            Id = new Guid("3eabb060-8923-468b-b530-d5b68e544b58"),
                            Id_Question = new Guid("f0869ff6-3127-4714-a75d-720d198c59e5"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B4-4"
                        },
                        new
                        {
                            Id = new Guid("9c4201ba-e32d-4e33-9514-12023d843c48"),
                            Id_Question = new Guid("f0869ff6-3127-4714-a75d-720d198c59e5"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B4-4"
                        },
                        new
                        {
                            Id = new Guid("9a2a82a3-b504-487e-a302-b293ac9921fc"),
                            Id_Question = new Guid("f0869ff6-3127-4714-a75d-720d198c59e5"),
                            IsAnswer = 0,
                            IsDeleted = 0,
                            Name = "Ans B4-4"
                        });
                });

            modelBuilder.Entity("MarvicSolution.DATA.Entities.App_User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Password")
                        .IsUnique()
                        .HasFilter("[Password] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("App_User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e341a8f6-dc1b-4829-94fb-316b6bac99b6"),
                            Department = "Khoang 1 HN",
                            Email = "khanhnd@gmail.com",
                            FullName = "Nguyen Duy Khanh",
                            IsDeleted = 0,
                            JobTitle = "Project Manager",
                            Organization = "Company TechNo1",
                            Password = "$2a$11$D57iJclK1BhZgg9B0P4I2.9sq0MoQIRImA8YeDVvbxeKPNG/KuTMK",
                            PhoneNumber = "0989878767",
                            UserName = "KhanhND"
                        },
                        new
                        {
                            Id = new Guid("346f2520-6295-4734-8868-6ca75258e7c1"),
                            Department = "Khoang 2 HCM",
                            Email = "nhantt@gmail.com",
                            FullName = "Tran Thien Nhan",
                            IsDeleted = 0,
                            JobTitle = "Member Job Title",
                            Organization = "Company PizzaHub",
                            Password = "$2a$11$MjbSthPb/xXnLsaNnJDVE.GGHoWL9aPMqLzCXTmoVs1HoHBqLsuWq",
                            PhoneNumber = "0336355563",
                            UserName = "NhanTT"
                        },
                        new
                        {
                            Id = new Guid("7a370bac-b796-454d-84cf-18c603102ca2"),
                            Department = "Khoang 10 DN",
                            Email = "nhant1@gmail.com",
                            FullName = "Tran Thanh Nhan",
                            IsDeleted = 0,
                            JobTitle = "Director",
                            Organization = "Company Marketing Hanzu",
                            Password = "$2a$11$IM2wFUFnOP.TYaxfqYjEluUatAmE95HIFZcElLoLGRmdUYkBFujCm",
                            PhoneNumber = "0345677456",
                            UserName = "NhanTTT1"
                        });
                });

            modelBuilder.Entity("MarvicSolution.DATA.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Create_Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id_Issue")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_ParentComment")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_User")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Is_Delete")
                        .HasColumnType("int");

                    b.Property<DateTime>("Update_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6bc52009-c246-4d54-a739-5d826ea3a7cc"),
                            Content = "NhanTTT1 comment",
                            Create_Date = new DateTime(2022, 4, 23, 22, 41, 10, 419, DateTimeKind.Local).AddTicks(2090),
                            Id_Issue = new Guid("7c2cc804-4aae-4af2-9191-4268fc02edc0"),
                            Id_ParentComment = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_User = new Guid("7a370bac-b796-454d-84cf-18c603102ca2"),
                            Is_Delete = 0,
                            Update_Date = new DateTime(2022, 4, 23, 22, 41, 10, 419, DateTimeKind.Local).AddTicks(6890)
                        },
                        new
                        {
                            Id = new Guid("d6581c11-c147-420e-9d2b-c47564fc013a"),
                            Content = "KhanhND comment",
                            Create_Date = new DateTime(2022, 4, 23, 23, 41, 10, 419, DateTimeKind.Local).AddTicks(7768),
                            Id_Issue = new Guid("7c2cc804-4aae-4af2-9191-4268fc02edc0"),
                            Id_ParentComment = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_User = new Guid("e341a8f6-dc1b-4829-94fb-316b6bac99b6"),
                            Is_Delete = 0,
                            Update_Date = new DateTime(2022, 4, 23, 23, 41, 10, 419, DateTimeKind.Local).AddTicks(7875)
                        });
                });

            modelBuilder.Entity("MarvicSolution.DATA.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attachment_Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Id_Assignee")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id_IssueType")
                        .HasColumnType("int");

                    b.Property<Guid?>("Id_Label")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Id_Linked_Issue")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Id_Parent_Issue")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Project")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Id_Reporter")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Id_Restrict")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Id_Sprint")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Id_Stage")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Id_Updator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<int?>("IsFlagged")
                        .HasColumnType("int");

                    b.Property<int?>("IsWatched")
                        .HasColumnType("int");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("Story_Point_Estimate")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Issue");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb2b349b-1075-45ca-96de-9f709a678eb0"),
                            Attachment_Path = "",
                            DateCreated = new DateTime(2022, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnd = new DateTime(2022, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2022, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Des epic Project A",
                            Id_Assignee = new Guid("e341a8f6-dc1b-4829-94fb-316b6bac99b6"),
                            Id_Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_IssueType = 1,
                            Id_Label = new Guid("ee7d776c-4c13-4cb9-a4fa-79b2d096a267"),
                            Id_Linked_Issue = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_Parent_Issue = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_Project = new Guid("a42b223b-faec-48e3-8e28-51fe1b22fa7c"),
                            Id_Reporter = new Guid("346f2520-6295-4734-8868-6ca75258e7c1"),
                            Id_Restrict = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_Sprint = new Guid("d2da18bc-3f2d-4558-acc8-480df6d770f4"),
                            Id_Stage = new Guid("d72506eb-ad2a-48d5-8caa-d322ee88811f"),
                            Id_Updator = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = 0,
                            IsFlagged = 0,
                            IsWatched = 0,
                            Priority = 5,
                            Story_Point_Estimate = 8,
                            Summary = "The epic of Project A",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7c2cc804-4aae-4af2-9191-4268fc02edc0"),
                            Attachment_Path = "",
                            DateCreated = new DateTime(2022, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnd = new DateTime(2022, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2022, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Des Story of Project A",
                            Id_Assignee = new Guid("e341a8f6-dc1b-4829-94fb-316b6bac99b6"),
                            Id_Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_IssueType = 2,
                            Id_Label = new Guid("ee7d776c-4c13-4cb9-a4fa-79b2d096a267"),
                            Id_Linked_Issue = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_Parent_Issue = new Guid("bb2b349b-1075-45ca-96de-9f709a678eb0"),
                            Id_Project = new Guid("a42b223b-faec-48e3-8e28-51fe1b22fa7c"),
                            Id_Reporter = new Guid("346f2520-6295-4734-8868-6ca75258e7c1"),
                            Id_Restrict = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_Sprint = new Guid("d2da18bc-3f2d-4558-acc8-480df6d770f4"),
                            Id_Stage = new Guid("d72506eb-ad2a-48d5-8caa-d322ee88811f"),
                            Id_Updator = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = 0,
                            IsFlagged = 0,
                            IsWatched = 0,
                            Priority = 3,
                            Story_Point_Estimate = 9,
                            Summary = "The Story of Project A",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("edff3f58-7640-4f5a-ada0-dc017f602501"),
                            Attachment_Path = "",
                            DateCreated = new DateTime(2022, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnd = new DateTime(2022, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2022, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Des Task1 of Project A",
                            Id_Assignee = new Guid("e341a8f6-dc1b-4829-94fb-316b6bac99b6"),
                            Id_Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_IssueType = 3,
                            Id_Label = new Guid("ee7d776c-4c13-4cb9-a4fa-79b2d096a267"),
                            Id_Linked_Issue = new Guid("7c2cc804-4aae-4af2-9191-4268fc02edc0"),
                            Id_Parent_Issue = new Guid("bb2b349b-1075-45ca-96de-9f709a678eb0"),
                            Id_Project = new Guid("a42b223b-faec-48e3-8e28-51fe1b22fa7c"),
                            Id_Reporter = new Guid("346f2520-6295-4734-8868-6ca75258e7c1"),
                            Id_Restrict = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_Sprint = new Guid("d2da18bc-3f2d-4558-acc8-480df6d770f4"),
                            Id_Stage = new Guid("d72506eb-ad2a-48d5-8caa-d322ee88811f"),
                            Id_Updator = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = 0,
                            IsFlagged = 0,
                            IsWatched = 0,
                            Priority = 3,
                            Story_Point_Estimate = 5,
                            Summary = "The Task1 of Project A",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("24c577bb-002d-4a31-a855-ca22f0c7ca69"),
                            Attachment_Path = "",
                            DateCreated = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnd = new DateTime(2022, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2022, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Des Task2 of Project A",
                            Id_Assignee = new Guid("e341a8f6-dc1b-4829-94fb-316b6bac99b6"),
                            Id_Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_IssueType = 3,
                            Id_Label = new Guid("ee7d776c-4c13-4cb9-a4fa-79b2d096a267"),
                            Id_Linked_Issue = new Guid("7c2cc804-4aae-4af2-9191-4268fc02edc0"),
                            Id_Parent_Issue = new Guid("bb2b349b-1075-45ca-96de-9f709a678eb0"),
                            Id_Project = new Guid("a42b223b-faec-48e3-8e28-51fe1b22fa7c"),
                            Id_Reporter = new Guid("346f2520-6295-4734-8868-6ca75258e7c1"),
                            Id_Restrict = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_Sprint = new Guid("d2da18bc-3f2d-4558-acc8-480df6d770f4"),
                            Id_Stage = new Guid("d72506eb-ad2a-48d5-8caa-d322ee88811f"),
                            Id_Updator = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = 0,
                            IsFlagged = 0,
                            IsWatched = 0,
                            Priority = 4,
                            Story_Point_Estimate = 2,
                            Summary = "The Task2 of Project A",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bbbe8f8e-a735-4a4c-bded-e4ce2405e8e1"),
                            Attachment_Path = "",
                            DateCreated = new DateTime(2022, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnd = new DateTime(2022, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2022, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Des epic of Project B",
                            Id_Assignee = new Guid("e341a8f6-dc1b-4829-94fb-316b6bac99b6"),
                            Id_Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_IssueType = 1,
                            Id_Label = new Guid("ee7d776c-4c13-4cb9-a4fa-79b2d096a267"),
                            Id_Linked_Issue = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_Parent_Issue = new Guid("bbbe8f8e-a735-4a4c-bded-e4ce2405e8e1"),
                            Id_Project = new Guid("89fad9a0-690d-46e8-a2fe-c6cc50350eaf"),
                            Id_Reporter = new Guid("346f2520-6295-4734-8868-6ca75258e7c1"),
                            Id_Restrict = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_Sprint = new Guid("87038ca8-11a7-4392-9c3e-86fd04f75223"),
                            Id_Stage = new Guid("d72506eb-ad2a-48d5-8caa-d322ee88811f"),
                            Id_Updator = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = 0,
                            IsFlagged = 0,
                            IsWatched = 0,
                            Priority = 2,
                            Story_Point_Estimate = 6,
                            Summary = "The epic of Project B",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bffc9087-de0d-4bf8-97a1-f97a26d6fda4"),
                            Attachment_Path = "",
                            DateCreated = new DateTime(2022, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnd = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2022, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Des Story of Project B",
                            Id_Assignee = new Guid("e341a8f6-dc1b-4829-94fb-316b6bac99b6"),
                            Id_Creator = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_IssueType = 2,
                            Id_Label = new Guid("ee7d776c-4c13-4cb9-a4fa-79b2d096a267"),
                            Id_Linked_Issue = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_Parent_Issue = new Guid("bbbe8f8e-a735-4a4c-bded-e4ce2405e8e1"),
                            Id_Project = new Guid("89fad9a0-690d-46e8-a2fe-c6cc50350eaf"),
                            Id_Reporter = new Guid("346f2520-6295-4734-8868-6ca75258e7c1"),
                            Id_Restrict = new Guid("00000000-0000-0000-0000-000000000000"),
                            Id_Sprint = new Guid("87038ca8-11a7-4392-9c3e-86fd04f75223"),
                            Id_Stage = new Guid("d72506eb-ad2a-48d5-8caa-d322ee88811f"),
                            Id_Updator = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = 0,
                            IsFlagged = 0,
                            IsWatched = 0,
                            Priority = 5,
                            Story_Point_Estimate = 1,
                            Summary = "The Story of Project B",
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MarvicSolution.DATA.Entities.Member", b =>
                {
                    b.Property<Guid>("Id_Project")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_User")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id_Project", "Id_User");

                    b.ToTable("Member");

                    b.HasData(
                        new
                        {
                            Id_Project = new Guid("a42b223b-faec-48e3-8e28-51fe1b22fa7c"),
                            Id_User = new Guid("e341a8f6-dc1b-4829-94fb-316b6bac99b6"),
                            Role = 3
                        },
                        new
                        {
                            Id_Project = new Guid("a42b223b-faec-48e3-8e28-51fe1b22fa7c"),
                            Id_User = new Guid("346f2520-6295-4734-8868-6ca75258e7c1"),
                            Role = 1
                        },
                        new
                        {
                            Id_Project = new Guid("89fad9a0-690d-46e8-a2fe-c6cc50350eaf"),
                            Id_User = new Guid("e341a8f6-dc1b-4829-94fb-316b6bac99b6"),
                            Role = 2
                        },
                        new
                        {
                            Id_Project = new Guid("89fad9a0-690d-46e8-a2fe-c6cc50350eaf"),
                            Id_User = new Guid("346f2520-6295-4734-8868-6ca75258e7c1"),
                            Role = 1
                        },
                        new
                        {
                            Id_Project = new Guid("a5329d06-9d32-4a54-b816-906dfbbd288c"),
                            Id_User = new Guid("e341a8f6-dc1b-4829-94fb-316b6bac99b6"),
                            Role = 3
                        });
                });

            modelBuilder.Entity("MarvicSolution.DATA.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Access")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id_Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Lead")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Updator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<int>("IsStared")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a42b223b-faec-48e3-8e28-51fe1b22fa7c"),
                            Access = 1,
                            DateCreated = new DateTime(2021, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnd = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2021, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Creator = new Guid("7a370bac-b796-454d-84cf-18c603102ca2"),
                            Id_Lead = new Guid("7a370bac-b796-454d-84cf-18c603102ca2"),
                            Id_Updator = new Guid("7a370bac-b796-454d-84cf-18c603102ca2"),
                            IsDeleted = 0,
                            IsStared = 0,
                            Key = "PA",
                            Name = "Project A",
                            UpdateDate = new DateTime(2021, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("89fad9a0-690d-46e8-a2fe-c6cc50350eaf"),
                            Access = 3,
                            DateCreated = new DateTime(2021, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnd = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2021, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Creator = new Guid("7a370bac-b796-454d-84cf-18c603102ca2"),
                            Id_Lead = new Guid("7a370bac-b796-454d-84cf-18c603102ca2"),
                            Id_Updator = new Guid("7a370bac-b796-454d-84cf-18c603102ca2"),
                            IsDeleted = 0,
                            IsStared = 1,
                            Key = "PB",
                            Name = "Project B",
                            UpdateDate = new DateTime(2021, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a5329d06-9d32-4a54-b816-906dfbbd288c"),
                            Access = 2,
                            DateCreated = new DateTime(2021, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateEnd = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStarted = new DateTime(2021, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Creator = new Guid("7a370bac-b796-454d-84cf-18c603102ca2"),
                            Id_Lead = new Guid("7a370bac-b796-454d-84cf-18c603102ca2"),
                            Id_Updator = new Guid("7a370bac-b796-454d-84cf-18c603102ca2"),
                            IsDeleted = 0,
                            IsStared = 1,
                            Key = "PC",
                            Name = "Project C",
                            UpdateDate = new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MarvicSolution.DATA.Entities.ProjectType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Creator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Updator")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77b88991-f823-4301-b452-1b14ca44d5cb"),
                            Creator = "User A",
                            IsDeleted = 0,
                            Name = "Marketing",
                            UpdateDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = "User A_Update"
                        },
                        new
                        {
                            Id = new Guid("21c68955-ea3e-4b41-8ec5-ef816c912f1a"),
                            Creator = "User B",
                            IsDeleted = 0,
                            Name = "Development Program",
                            UpdateDate = new DateTime(2021, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = "User B_Update"
                        },
                        new
                        {
                            Id = new Guid("cc6c38be-7461-4f0c-b3dd-722477375d61"),
                            Creator = "User C",
                            IsDeleted = 0,
                            Name = "Accounting",
                            UpdateDate = new DateTime(2015, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Updator = "User C_Update"
                        });
                });

            modelBuilder.Entity("MarvicSolution.DATA.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id_Test")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Scores")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da1969f2-3008-49d3-8281-030b4c343c5d"),
                            Id_Test = new Guid("43d27fb9-cdf2-4a42-aeac-30d551ad7334"),
                            IsDeleted = 0,
                            Name = "Question A1",
                            Scores = 2
                        },
                        new
                        {
                            Id = new Guid("5570f4ee-0f7d-4a48-be63-bc011555ddd2"),
                            Id_Test = new Guid("43d27fb9-cdf2-4a42-aeac-30d551ad7334"),
                            IsDeleted = 0,
                            Name = "Question A2",
                            Scores = 3
                        },
                        new
                        {
                            Id = new Guid("a8b3af9f-bae9-4b1a-89d0-808f7b8b4e56"),
                            Id_Test = new Guid("43d27fb9-cdf2-4a42-aeac-30d551ad7334"),
                            IsDeleted = 0,
                            Name = "Question A3",
                            Scores = 4
                        },
                        new
                        {
                            Id = new Guid("d60e8b27-d139-40d4-9cc8-3e8d09752a6a"),
                            Id_Test = new Guid("43d27fb9-cdf2-4a42-aeac-30d551ad7334"),
                            IsDeleted = 0,
                            Name = "Question A4",
                            Scores = 1
                        },
                        new
                        {
                            Id = new Guid("1d641d48-f550-481b-adff-440ed5aa6f65"),
                            Id_Test = new Guid("24b1c442-53a2-49be-a146-c2147540c645"),
                            IsDeleted = 0,
                            Name = "Question B1",
                            Scores = 6
                        },
                        new
                        {
                            Id = new Guid("b776ef62-50a5-4998-aa13-a6d3f4ca35e4"),
                            Id_Test = new Guid("24b1c442-53a2-49be-a146-c2147540c645"),
                            IsDeleted = 0,
                            Name = "Question B2",
                            Scores = 2
                        },
                        new
                        {
                            Id = new Guid("7cf4e8f0-9dd9-438d-8581-57d33ad90b78"),
                            Id_Test = new Guid("24b1c442-53a2-49be-a146-c2147540c645"),
                            IsDeleted = 0,
                            Name = "Question B3",
                            Scores = 1
                        },
                        new
                        {
                            Id = new Guid("5d6e0ec4-cbd9-43d9-8330-4b76405808ae"),
                            Id_Test = new Guid("24b1c442-53a2-49be-a146-c2147540c645"),
                            IsDeleted = 0,
                            Name = "Question B4",
                            Scores = 1
                        },
                        new
                        {
                            Id = new Guid("f0869ff6-3127-4714-a75d-720d198c59e5"),
                            Id_Test = new Guid("24b1c442-53a2-49be-a146-c2147540c645"),
                            IsDeleted = 0,
                            Name = "Question B5",
                            Scores = 1
                        });
                });

            modelBuilder.Entity("MarvicSolution.DATA.Entities.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Test");

                    b.HasData(
                        new
                        {
                            Id = new Guid("43d27fb9-cdf2-4a42-aeac-30d551ad7334"),
                            IsDeleted = 0,
                            Name = "Test A"
                        },
                        new
                        {
                            Id = new Guid("24b1c442-53a2-49be-a146-c2147540c645"),
                            IsDeleted = 0,
                            Name = "Test B"
                        },
                        new
                        {
                            Id = new Guid("d77a4a2d-d886-4658-9438-c800157423e0"),
                            IsDeleted = 0,
                            Name = "Test C"
                        },
                        new
                        {
                            Id = new Guid("32661992-aaa1-49d6-adba-cb55ebbf0c04"),
                            IsDeleted = 0,
                            Name = "Test D"
                        },
                        new
                        {
                            Id = new Guid("c475d804-0122-4b2b-af41-f6c53d22ba74"),
                            IsDeleted = 0,
                            Name = "Test E"
                        },
                        new
                        {
                            Id = new Guid("c7b0d387-afc8-423d-8218-a3fd83cc850e"),
                            IsDeleted = 0,
                            Name = "Test F"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
